import type {
  Campaign,
  Coupon,
  Member,
  PointTransaction,
  Promotion,
  Video,
} from "./types";

export const seedMembers: Member[] = [
  {
    id: "m-1001",
    name: "陳小蝦",
    email: "member@demo.hk",
    phone: "9123 4567",
    points: 1280,
    tier: "金蝦",
    status: "active",
    joinedAt: "2026-05-12",
  },
  {
    id: "m-1002",
    name: "李嘉怡",
    email: "kayi@example.hk",
    phone: "9234 5678",
    points: 760,
    tier: "銀蝦",
    status: "active",
    joinedAt: "2026-06-03",
  },
  {
    id: "m-1003",
    name: "何俊朗",
    email: "jason@example.hk",
    phone: "9345 6789",
    points: 320,
    tier: "新會員",
    status: "active",
    joinedAt: "2026-07-18",
  },
  {
    id: "m-1004",
    name: "周美琪",
    email: "miki@example.hk",
    phone: "9456 7890",
    points: 90,
    tier: "新會員",
    status: "inactive",
    joinedAt: "2026-08-01",
  },
];
export const seedTransactions: PointTransaction[] = [
  {
    id: "pt-1",
    memberId: "m-1001",
    memberName: "陳小蝦",
    venue: "lai-chi-kok",
    points: 180,
    reason: "到店消費積分",
    createdAt: "2026-08-26 21:30",
  },
  {
    id: "pt-2",
    memberId: "m-1002",
    memberName: "李嘉怡",
    venue: "kwun-tong",
    points: 120,
    reason: "到店消費積分",
    createdAt: "2026-08-25 19:15",
  },
  {
    id: "pt-3",
    memberId: "m-1001",
    memberName: "陳小蝦",
    venue: "all",
    points: -60,
    reason: "兌換會員禮遇",
    createdAt: "2026-08-20 18:40",
  },
];
export const seedCoupons: Coupon[] = [
  {
    id: "cp-1",
    title: "會員現金券",
    kind: "cash",
    discountAmount: 50,
    validFrom: "2026-08-01",
    validUntil: "2026-12-31",
    venueScope: "all",
    recipientIds: ["m-1001"],
    status: "active",
  },
  {
    id: "cp-2",
    title: "同行釣蝦優惠",
    kind: "threshold",
    minimumSpend: 300,
    discountAmount: 60,
    validFrom: "2026-08-01",
    validUntil: "2026-10-31",
    venueScope: "all",
    recipientIds: [],
    status: "active",
  },
];
export const seedPromotions: Promotion[] = [
  {
    id: "pr-1",
    title: "新會員迎新積分",
    category: "會員限定",
    content: "完成會員登記即可獲得迎新積分，兩間分店均可使用。",
    imageName: "venue-preview.jpg",
    imageUrl: "/brand/venue-preview.jpg",
    icon: "gift",
    status: "published",
    updatedAt: "2026-08-28",
  },
  {
    id: "pr-2",
    title: "平日晚場挑戰",
    category: "期間限定",
    content: "平日晚場限定活動，邀請朋友一起挑戰城市釣蝦體驗。",
    imageName: "venue-preview.jpg",
    imageUrl: "/brand/venue-preview.jpg",
    icon: "sparkles",
    status: "draft",
    updatedAt: "2026-08-27",
  },
];
export const seedVideos: Video[] = [
  {
    id: "vd-1",
    title: "一分鐘看懂釣蝦樂趣",
    status: "published",
    duration: "01:08",
    updatedAt: "2026-08-26",
    coverTone: "purple",
    fileName: "shrimp-intro.mp4",
    fileSizeMb: 38.6,
    pinned: true,
  },
  {
    id: "vd-2",
    title: "荔枝角店場內直擊",
    status: "draft",
    duration: "00:42",
    updatedAt: "2026-08-25",
    coverTone: "orange",
    fileName: "lai-chi-kok-tour.mp4",
    fileSizeMb: 24.2,
    pinned: false,
  },
];
export const seedCampaigns: Campaign[] = [
  {
    id: "em-1",
    subject: "週末釣蝦會員賞",
    audience: "所有活躍會員",
    sentAt: "2026-08-24 12:00",
    recipientCount: 3,
    recipientIds: ["m-1001", "m-1002", "m-1003"],
    body: "<p>今個週末，帶埋朋友來釣蝦王，一齊享受城市釣蝦樂趣！</p>",
  },
];
